### ISSUE TITLE
Convert the codebase to es6 module

### ISSUE THREAD

**Issue by rajchandra3** [TheByteAvenue/template-nodejs-api#1]
**What should you change?** A clear and concise description of what changes are
required

- Convert the entire project to es6.
Example: 
- convert `require` to `import`
- `module.export` to `exports` or `export default` accordingly

Make sure the app is working as expected at the end of the completion.

**Comment by ShubhamPalriwala** [comment]
I'd like to take this up !

**Comment by rajchandra3** [comment]
Cool, I have assigned it to you!

**Comment by ShubhamPalriwala** [comment]
Can I use Babel here since Nodejs uses Commonjs ?

**Comment by rajchandra3** [comment]
You can simply update your nodejs to latest unstable version.

The latest version has experimental support for esm.

**Comment by rajchandra3** [comment]
If you need further clarification, lmk.

**Comment by rajchandra3** [comment]
Are you still working on it? @ShubhamPalriwala

**Comment by ShubhamPalriwala** [comment]
Am facing some issues while doing `yarn install` !
I guess my OS got corrupt a while ago maybe that's the reason so it might take time for me to resolve this issue !
I will try do it once my OS is fixed.
If somebody else is up for taking it then I'm okay with it!

**Comment by rajchandra3** [comment]
version 0.0.8 upgrades codebase to es6.
